"""
用 Playwright 控制本机 Chromium：登录 B 站并保存会话，再导出为 yt-dlp 可用的 cookies.txt。
登录成功通过 B 站 nav 接口自动检测，无需在终端按 Enter。
"""
from __future__ import annotations

import json
import os
import re
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent
# 便携版：浏览器缓存放在项目目录，随文件夹拷贝（需准备脚本设置 PLAYWRIGHT_BROWSERS_PATH 并 install）
_pw_br = ROOT / "pw-browsers"
if _pw_br.is_dir():
    os.environ.setdefault("PLAYWRIGHT_BROWSERS_PATH", str(_pw_br.resolve()))
STATE_PATH = ROOT / "browser_state.json"
COOKIES_PATH = ROOT / "cookies.txt"

BILI_NAV_API = "https://api.bilibili.com/x/web-interface/nav"


def _page_is_logged_in(page) -> bool:
    """在页面上下文中带 Cookie 请求 nav，判断 isLogin。"""
    try:
        return bool(
            page.evaluate(
                """async () => {
  try {
    const r = await fetch(%r, { credentials: 'include' });
    const j = await r.json();
    return !!(j && j.code === 0 && j.data && j.data.isLogin === true);
  } catch (e) {
    return false;
  }
}"""
                % BILI_NAV_API
            )
        )
    except Exception:
        return False


def save_login_state(
    start_url: str = "https://passport.bilibili.com/pc/passport/login",
    state_path: Path | None = None,
    timeout_sec: float = 900.0,
    poll_interval_sec: float = 1.2,
) -> Path:
    """
    打开 Chromium，用户在窗口内完成登录；脚本轮询 nav 接口，检测到已登录即保存 storage_state。
    timeout_sec: 最长等待秒数（默认 15 分钟）。
    """
    from playwright.sync_api import sync_playwright

    path = state_path or STATE_PATH
    print("正在启动 Chromium（可见窗口）…", flush=True)
    deadline = time.monotonic() + timeout_sec
    last_print = 0.0
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        context = browser.new_context(locale="zh-CN")
        page = context.new_page()
        page.goto(start_url, wait_until="domcontentloaded")
        print(
            "请在浏览器窗口中完成 B 站登录（扫码/密码均可）。\n"
            "脚本会自动检测登录状态，无需回到终端按键。",
            flush=True,
        )
        while time.monotonic() < deadline:
            if _page_is_logged_in(page):
                page.wait_for_timeout(800)
                if _page_is_logged_in(page):
                    context.storage_state(path=str(path))
                    browser.close()
                    print(f"\n已检测到登录，会话已保存：{path}", flush=True)
                    return path
            now = time.monotonic()
            if now - last_print >= 8.0:
                left = int(max(0, deadline - now))
                print(f"…仍在等待登录（剩余约 {left // 60} 分 {left % 60} 秒）", flush=True)
                last_print = now
            page.wait_for_timeout(int(poll_interval_sec * 1000))
        browser.close()
    raise TimeoutError(f"{timeout_sec:.0f} 秒内未完成登录，请重试。")


def storage_state_to_netscape(state_path: Path, out_path: Path) -> int:
    """将 Playwright storage_state.json 转为 Netscape cookies.txt。返回写入条数。"""
    data = json.loads(state_path.read_text(encoding="utf-8"))
    cookies = data.get("cookies") or []
    lines: list[str] = [
        "# Netscape HTTP Cookie File",
        "# Generated by browser_bilibili.py for yt-dlp",
        "",
    ]
    n = 0
    for c in cookies:
        domain = (c.get("domain") or "").strip()
        if "bilibili" not in domain.lower():
            continue
        path_ = c.get("path") or "/"
        secure = "TRUE" if c.get("secure") else "FALSE"
        exp = c.get("expires")
        if isinstance(exp, (int, float)) and exp > 0:
            exp_int = int(exp)
        else:
            exp_int = 0
        name = c.get("name") or ""
        value = c.get("value") or ""
        if not name:
            continue
        # Netscape: domain, includeSubdomains, path, secure, expires, name, value
        domain_specified = "TRUE" if domain.startswith(".") else "FALSE"
        lines.append(f"{domain}\t{domain_specified}\t{path_}\t{secure}\t{exp_int}\t{name}\t{value}")
        n += 1
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return n


def ensure_cookies_from_state(state_path: Path | None = None) -> Path | None:
    """若存在 browser_state.json，则刷新 cookies.txt。"""
    sp = state_path or STATE_PATH
    if not sp.is_file():
        return None
    n = storage_state_to_netscape(sp, COOKIES_PATH)
    print(f"已导出 {n} 条 B 站相关 Cookie → {COOKIES_PATH}", flush=True)
    return COOKIES_PATH


SRT_BLOCK = re.compile(
    r"(\d+)\s*\n(\d{2}:\d{2}:\d{2},\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2},\d{3})\s*\n([\s\S]*?)(?=\n\d+\s*\n|\Z)",
    re.MULTILINE,
)


def parse_srt_to_lines(content: str) -> list[tuple[str, str]]:
    rows: list[tuple[str, str]] = []
    for m in SRT_BLOCK.finditer(content.strip() + "\n"):
        t = m.group(2)
        text = m.group(4).strip().replace("\r\n", "\n")
        text = re.sub(r"<[^>]+>", "", text)
        if text:
            rows.append((t, text))
    return rows


